### PR TITLE
Adds option to not log GET params

### PR DESCRIPTION
**Pull request by timgent**

### CODE REVIEW

**Comment by easternbloc** [comment]
As we already use require('url') perhaps we can just get the pathname from the url? 
```
urlObject.pathname
```
https://nodejs.org/api/url.html

What do you think?

**Comment by timgent** [comment]
Tried this but it doesn't include the whole URL. You'd need to stitch together protocol, root, and pathname (or something like that). Happy to do that if you reckon it's neater

**Comment by easternbloc** [comment]
Hmm, I kinda realised that after I'd posted it. I think i'm still more comfortable with using url and stiching it together. Maybe the same happens underneath but least it's fully tested that way.

**Comment by timgent** [comment]
Sure

**Comment by timgent** [comment]
@easternbloc Updated

**Comment by easternbloc** [comment]
👌

**Pull request merged**
